name: CI
on: [push]
permissions:
  contents: read
jobs:
  main:
    name: pnpm commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set Node.js version
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 #v6.0.9
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Format check
        run: pnpm run format:check
